name: Deploy Components to Testnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: NEARBuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      deploy-env: "testnet"
      build-env: "testnet"
      app-name: "mintbos-marketplace-template"
      deploy-account-address: "mintbos.testnet"
      signer-account-address: "mintbos.testnet"
      signer-public-key: "ed25519:FoMeGdCFbLFbsxwGtC1hP4s7TVXxhUPAkMkmRFRTS5g7"
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.TESTNET_SIGNER_PRIVATE_KEY }}
