name: Deploy Components to Testnet
on:
  push:
    branches: [develop]
jobs:
  deploy-mainnet:
    uses: NEARBuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      deploy-env: "testnet"
      app-name: "bos-blackdragon-marketplace"
      deploy-account-address: blackdragon.testnet
      signer-account-address: blackdragon.testnet
      signer-public-key: ${{ vars.TESTNET_BLACKDRAGON_MARKETPLACE_PUBLIC_KEY }}
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.TESTNET_BLACKDRAGON_MARKETPLACE_SIGNER_KEY }}
